name: Run PowerShell Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v5
        
    - name: Install Pester
      shell: pwsh
      run: |
        Install-Module -Name Pester -Force -Scope CurrentUser -SkipPublisherCheck -RequiredVersion 5.5.0
        
    - name: Run Tests
      shell: pwsh
      run: |
        $config = New-PesterConfiguration
        $config.Run.Path = 'SwmfsMonitor.Tests.ps1'
        $config.TestResult.Enabled = $true
        $config.TestResult.OutputFormat = 'NUnitXml'
        $config.TestResult.OutputPath = 'TestResults.xml'
        $config.Output.Verbosity = 'Detailed'
        Invoke-Pester -Configuration $config
        
    - name: Check if test results exist
      shell: pwsh
      run: |
        if (Test-Path "TestResults.xml") {
          Write-Host "Test results file found"
          Get-Content "TestResults.xml" | Select-Object -First 10
        } else {
          Write-Host "Test results file not found"
          exit 1
        }
        
    - name: Publish Test Results
      uses: dorny/test-reporter@v2
      if: success() || failure()
      with:
        name: PowerShell Tests
        path: TestResults.xml
        reporter: dotnet-nunit
        fail-on-error: true
